# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_auto_20160926_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='location',
            field=models.CharField(choices=[('pantry', 'Pantry'), ('fridge', 'Fridge'), ('freezer', 'Freezer')], max_length=10, null=True),
        ),
    ]
