# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0008_ingredient_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifespan',
            name='freezer',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lifespan',
            name='fridge',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lifespan',
            name='room_temperature',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
