# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0009_auto_20160929_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
