# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 04:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0013_delete_hello'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set([('user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set([('recipe', 'name'), ('recipe', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='recipeinstruction',
            unique_together=set([('recipe', 'number')]),
        ),
    ]
